version: "3"
services:
  mypage:
    build: ./MyPage
    ports:
      - "3000:3000"
  chatbot:
    build: ./SimpleChatBot
    ports:
      - "3001:3001"
    volumes:
      - /home/MyPage/chatbot/data:/usr/src/app/data
  roller:
    build: ./CardRoller
    ports:
      - "3002:3002"
