version: "3"
networks:
  gitea:
    external: false
services:
  drone:
    image: drone/drone
    env_file: setting/.env
    environment:
      - DRONE_SERVER_HOST=docs.littlehumming.cn
      - DRONE_SERVER_PROTO=http
    restart: always
    volumes:
      - ./data/drone:/data
    ports:
      - "3006:80"
      
  drone-runner:
    image: drone/drone-runner-docker
    env_file: setting/.env
    environment:
      - DRONE_RPC_HOST=docs.littlehumming.cn
      - DRONE_RUNNER_NAME=runner
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RPC_PROTO=https
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  gitea-server:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_PORT=222
      - SSH_LISTEN_PORT=22
      - DOMAIN=www.littlehumming.cn
      - SSH_DOMAIN=www.littlehumming.cn
      - ROOT_URL=https://www.littlehumming.cn/gitea
      - LOCAL_ROOT_URL=http://localhost:3000
    restart: always
    networks:
      - gitea
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3005:3000"
      - "222:22"

  mypage:
    build: ./MyPage
    ports:
      - "3000:3000"

  chatbot:
    build: ./SimpleChatBot
    ports:
      - "3001:3001"
    volumes:
      - /home/MyPage/chatbot/data:/usr/src/app/data

  roller:
    build: ./CardRoller
    ports:
      - "3002:3002"
    volumes:
      - /home/MyPage/cardRoller/data:/usr/src/app/data
