version: '3'
services:
  mypage:
    build: ./MyPage
    ports:
      - "3000:3000"
    # volumes:
    #   - /home/MyPage/app:/usr/src/app
  chatbot:
    build: ./SimpleChatBot
    ports:
      - "3001:3001"